### PR TITLE
ADM-338 add log for gradle test

### PR DESCRIPTION
**Pull request by Devonzhang**
## Before

./gradlew test no info out put

Screenshot 2023-01-12 at 10 52 54

## After

./gradlew test with test info run by this command in console

Screenshot 2023-01-12 at 10 52 39

### CODE REVIEW

**Review by guzhongren — APPROVED** [review]
LGTM

**Comment by guzhongren** [comment]
It's better to add test coverge check for test, https://docs.gradle.org/current/userguide/jacoco_plugin.html#sec:jacoco_report_violation_rules
And it's good to set the all metrics to 100%

**Comment by Devonzhang** [comment]
> 

Hi, there is a HeartbeatApplication file is not covered cause it's the spring application file and no need to test it, but this will cause failure when we set all metrics to 100%, can we only set it to 70%?
Screenshot 2023-01-12 at 13 32 48

**Comment by huijunnnn** [comment]
> It's better to add test coverge check for test, https://docs.gradle.org/current/userguide/jacoco_plugin.html#sec:jacoco_report_violation_rules And it's good to set the all metrics to 100%
Hi,I have added test coverge check for test, and the result ,please see the following picture.
Screenshot 2023-01-12 at 13 58 00

**Review by huijunnnn — APPROVED** [review]
LGFM

**Pull request merged**
