### PR TITLE
issue#346 [Bug] fix backend Swagger

### PR DESCRIPTION
**Pull request by allenzph**
## Summary

...

## Before

_Description_

**Screenshots**
If applicable, add screenshots to help explain behavior of your code.

## After

_Description_

**Screenshots**
If applicable, add screenshots to help explain behavior of your code.

## Note

_Null_

### CODE REVIEW

**Comment by allenzph** [comment]
the reason of changing the dependency is here: https://stackoverflow.com/questions/74701738/spring-boot-3-springdoc-openapi-ui-doesnt-work

**Comment by guzhongren** [comment]
Hey, @allenzph 
Thx for your contribution
Could u upload a screenshot for this bug fix? 
thx

**Comment by allenzph** [comment]
image

**Review by guzhongren — APPROVED** [review]
Nice job

**Pull request merged**
